/*
 * Alzachat lib runnable class definition.
 * Copyright (c) 2021 Alzachat. All rights reserved.
 *                  Ali Forouzan
 */

#ifndef ALZACHAT_SERVERRUNNABLE_H
#define ALZACHAT_SERVERRUNNABLE_H


#include <QRunnable>
#include <QTcpSocket>


// Q_OBJECT missing in the original file generated by class wizard.
// because we set this class with base class QRunnable
// with no inheritance in the class wizard
// We do not have this. So, we cannot use signal/slot
// But we need them.
// Thus, we should use multiple inheritance: QObject inserted here

class ServerRunnable : public QObject, public QRunnable {
	Q_OBJECT
    public:
	ServerRunnable();
	qintptr socketDescriptor;
	int (*func)(void *);
	void *funcData;

    signals:
	// notify to the main thread when we're done
	void Result(int Number);

    protected:
	virtual void run();

};


#endif //ALZACHAT_SERVERRUNNABLE_H
